package backend;

import intermediate.ICode;
import intermediate.SymTab;
import message.MessageHandler;

/**
 * <h1>Backend</h1>
 * <p>the framework class that represents the back end component</p>
 */
public abstract class Backend {

    protected static MessageHandler messageHandler = new MessageHandler();
    /**
     * Symbol table
     */
    protected SymTab symTab;
    /**
     * Intermediate code
     */
    protected ICode iCode;

    /**
     * Process the intermediate code and the symbol table generated by the parser. To be implemneted by a compiler or an
     * interpreter subclass.
     * @param iCode the intermediate code
     * @param symTab the symbol table
     * @throws Exception if an error occurred
     */
    public abstract void process(ICode iCode, SymTab symTab) throws Exception;
}
